development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: pepega
  password: pepega

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: pepega
  password: pepega

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: pepega
  password: pepega
